SCOPES = [
    "Calendars.Read",
    "Calendars.Read.Shared",
    "Calendars.ReadBasic",
    "Calendars.ReadWrite",
    "Calendars.ReadWrite.Shared",
    "Contacts.Read",
    "Contacts.ReadWrite",
    "Contracts.Read.All",
    "email",
    "Files.Read",
    "Files.Read.All",
    "Files.ReadWrite",
    "Files.ReadWrite.All",
    "Files.ReadWrite.AppFolder",
    "Mail.Read",
    "Mail.Read.Shared",
    "Mail.ReadBasic",
    "Mail.ReadBasic.Shared",
    "Mail.ReadWrite",
    "Mail.ReadWrite.Shared",
    "Mail.Send",
    "Mail.Send.Shared",
    "Notes.ReadWrite",
    "offline_access",
    "openid",
    "profile",
    "Tasks.Read",
    "Tasks.Read.Shared",
    "Tasks.ReadWrite",
    "Tasks.ReadWrite.Shared",
    "User.Read",
]

REDIRECT_URI = "http://localhost:8080/auth/callback"
